sudo: required

language: go

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz

script:
  - go test ./...

deploy:
  provider: gae
  keyfile: client-secret.json
  project: go-tunefy
  on: master
