sudo: required

language: go

services:
  - docker

env:
  - IMAGE=anapaulagomes/go-tunefy

before_install:
  - docker build -t ${IMAGE} .
  - docker run -d -p 8181:8181 ${IMAGE}

script:
  - go test ./...
